version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana_data:/var/lib/grafana

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ./influx_data:/var/lib/influxdb

  node-red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nodered_data:/data

  mosquitto-mqtt:
    image: eclipse-mosquitto
    restart: on-failure
    container_name: mosquitto
    ports:
      - "1883:1883"

  mqtt_listener:
    network_mode: "bridge"
    restart: on-failure
    env_file:
     - ./mqttListener/mqtt.env
    build:
      context: mqttListener/
      dockerfile: dockerfile
  e3dc_scheduler:
    network_mode: "bridge"
    restart: on-failure
    build:
      context: e3dcScheduler/
      dockerfile: dockerfile
    env_file:
     - ./e3dcScheduler/service.env
