version: "3"
services:
  mqtt_listener:
    network_mode: "bridge"
    restart: on-failure
    env_file:
     - ./mqttListener/mqtt.env
    build:
      context: mqttListener/
      dockerfile: dockerfile
  e3dc_scheduler:
    network_mode: "bridge"
    restart: on-failure
    build:
      context: e3dcScheduler/
      dockerfile: dockerfile
    env_file:
     - ./e3dcScheduler/service.env