version: "3"
services:
  grafana:
    image: grafana/grafana
    init: true
    ports:
      - "3000:3000"
    restart: always
    networks:
      - adfsmarthome
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./.docker/grafana_data:/var/lib/grafana

  influxdb:
    image: influxdb:2.0
    init: true
    networks:
      - adfsmarthome
    ports:
      - "8086:8086"
    env_file: ./influxdb/influxdb.env
    restart: always
    volumes:
      - ./.docker/influxData:/var/lib/influxdb2

  node-red:
    image: nodered/node-red:latest
    init: true
    networks:
      - adfsmarthome
    ports:
      - "1880:1880"
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./.docker/nodered_data:/data

  e3dc_scheduler:
    restart: always
    init: true
    networks:
      - adfsmarthome
    build:
      context: e3dcScheduler/
      dockerfile: dockerfile
    env_file: ./e3dcScheduler/service.env

  mqttservice:
    restart: always
    init: true
    depends_on: 
      - mqttserver
      - rabbitmq
    networks:
      - adfsmarthome
    build:
      context: mqttService/
      dockerfile: Dockerfile

  timeseries:
    restart: always
    init: true
    depends_on: 
      - influxdb
      - rabbitmq
    networks:
      - adfsmarthome
    build:
      context: TimeSeriesCollector/
      dockerfile: Dockerfile

  mqttserver:
    restart: always
    init: true
    networks:
      - adfsmarthome
    container_name: mosca_mqtt
    image: matteocollina/mosca
    ports:
      - 1883:1883    

  rabbitmq:
    image: rabbitmq:3.6-management
    init: true
    networks:
      - adfsmarthome
    container_name: rabbitmq
    restart: always
    hostname: adfrabbit
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/


  # zigbee2mqtt:
  #   container_name: zigbee2mqtt
  #   image: koenkk/zigbee2mqtt
  #   networks:
  #     - adfsmarthome
  #   volumes:
  #     - ./.docker/zigbee:/app/data
  #     - /run/udev:/run/udev:ro
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   restart: always
  #   privileged: true
  #   environment:
  #     - TZ=Europe/Amsterdam

networks:
  adfsmarthome:
